<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>AIHappey.Desktop.UiTests</RootNamespace>
    <ApplicationManifest>../../Samples/AIHappey.Desktop.HeaderAuth/app.manifest</ApplicationManifest>
    <Platforms>x64</Platforms>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <UseWinUI>true</UseWinUI>
    <WinUISDKReferences>false</WinUISDKReferences>
    <WindowsPackageType>None</WindowsPackageType>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <SelfContained>true</SelfContained>
    <EnableMsixTooling>false</EnableMsixTooling>
    <EnableWinAppRunSupport>false</EnableWinAppRunSupport>
    <PublishTrimmed>false</PublishTrimmed>
    <PublishReadyToRun>false</PublishReadyToRun>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <DefaultLanguage>en</DefaultLanguage>
  </PropertyGroup>
  <ItemGroup>
    <PRIResource Include="..\..\Core\AIHappey.Desktop.Core\Strings\**\*.resw" Link="Strings\%(RecursiveDir)%(Filename)%(Extension)" />
    <Manifest Include="$(ApplicationManifest)" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.29648.1000-preview" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.8.260921001" />
    <ProjectReference Include="../../Core/AIHappey.Desktop.Core/AIHappey.Desktop.Core.csproj" />
  </ItemGroup>
</Project>
